# ####### Agency
# POST http://localhost:7777/agency/create HTTP/1.1
# Content-Type: application/json

# {
#     "name":"UNDP"
# }

# GET http://localhost:7777/agency/get/4

# PATCH http://localhost:7777/agency/update HTTP/1.1
# Content-Type: application/json

# {
#     "id":4,
#     "name":"UNICEF"
# }

# DELETE http://localhost:7777/agency/delete/3

################Agent
# POST http://localhost:7777/agent/create HTTP/1.1
# Content-Type: application/json

# {
#     "name":"kwangyel11",
#     "type":"person",
#     "idNumber": "10503000532",
#     "agencyId":4
# }


# GET http://localhost:7777/agent/get/1

# PATCH http://localhost:7777/agent/update HTTP/1.1
# Content-Type: application/json

# {
#     "id":1,
#     "name":"anon"
# }

# DELETE http://localhost:7777/agent/delete/1



##################Movement

# POST http://localhost:7777/movement/create HTTP/1.1
# Content-Type: application/json

# {
#     "agentId":3,
#     "type":"person",
#     "time":"2021-03-15",
#     "visitorType":"car",
#     "requestId":null
# }


# GET http://localhost:7777/movement/get/1

# PATCH http://localhost:7777/movement/update HTTP/1.1
# Content-Type: application/json

# {
#     "id":1,
#     "type":"person"
# }

# DELETE http://localhost:7777/movement/delete/1




###########Reqeust

# POST http://localhost:7777/request/create HTTP/1.1
# Content-Type: application/json

# {
#     "requesterId":3,
#     "name":"fried",
#     "time":"2021-03-15",
#     "type":"person"
# }


# GET http://localhost:7777/request/get/1

# PATCH http://localhost:7777/request/update HTTP/1.1
# Content-Type: application/json

# {
#     "id":1,
#     "type":"car"
# }

# DELETE http://localhost:7777/request/delete/1

